#ifndef LCD_ASSETS_h
#define LCD_ASSETS_h

#include "Arduino.h"

#include "assets/Boot.h"
#include "assets/Choose_NutriScale.h"
#include "assets/Choose_Universal.h"
#include "assets/Code_Input.h"
#include "assets/Code_Success.h"
#include "assets/Dashboard.h"
#include "assets/Error.h"
#include "assets/Loading.h"
#include "assets/Output.h"
#include "assets/Weight_Scalling.h"
#include "assets/Battery_Full.h"
#include "assets/Battery_Half.h"
#include "assets/Battery_Low.h"
#include "icon/Cerealia.h"
#include "icon/Drink.h"
#include "icon/Egg.h"
#include "icon/Fish.h"
#include "icon/Fruits.h"
#include "icon/Meat.h"
#include "icon/Milk.h"
#include "icon/Nuts.h"
#include "icon/Oil.h"
#include "icon/Roots.h"
#include "icon/Spice.h"
#include "icon/Sugar.h"
#include "icon/Unknown.h"
#include "icon/Vegetable.h"
#include "assets/Choose_Menu_1.h"
#include "assets/Choose_Menu_2.h"
#include "assets/Choose_Menu_3.h"
#include "assets/Choose_Menu_4.h"

#include "assets/Code_Input_Rev.h"
#include "assets/Setting_BTON.h"
#include "assets/Setting_BTOFF.h"
#include "assets/Setting_Info.h"
#include "assets/NotFound.h"

#include "assets/Setting.h"
#include "assets/Calibration.h"
#include "assets/Save_Calibration.h"
#include "assets/soon.h"

#endif // LCD_ASSETS_h